// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file cmd.proto (package wire, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cmd.proto.
 */
export const file_cmd: GenFile = /*@__PURE__*/
  fileDesc("CgljbWQucHJvdG8SBHdpcmUiJAoHQ29tbWFuZBILCgNjbWQYASABKAkSDAoEYXJncxgCIAMoCUIIWgYuL3dpcmViBnByb3RvMw");

/**
 * @generated from message wire.Command
 */
export type Command = Message<"wire.Command"> & {
  /**
   * @generated from field: string cmd = 1;
   */
  cmd: string;

  /**
   * @generated from field: repeated string args = 2;
   */
  args: string[];
};

/**
 * Describes the message wire.Command.
 * Use `create(CommandSchema)` to create a new message.
 */
export const CommandSchema: GenMessage<Command> = /*@__PURE__*/
  messageDesc(file_cmd, 0);

